// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/nicholasjackson/building-microservices-youtube/product-api/sdk/models"
)

// NewUpdateProductParams creates a new UpdateProductParams object
// with the default values initialized.
func NewUpdateProductParams() *UpdateProductParams {
	var ()
	return &UpdateProductParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateProductParamsWithTimeout creates a new UpdateProductParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateProductParamsWithTimeout(timeout time.Duration) *UpdateProductParams {
	var ()
	return &UpdateProductParams{

		timeout: timeout,
	}
}

// NewUpdateProductParamsWithContext creates a new UpdateProductParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateProductParamsWithContext(ctx context.Context) *UpdateProductParams {
	var ()
	return &UpdateProductParams{

		Context: ctx,
	}
}

// NewUpdateProductParamsWithHTTPClient creates a new UpdateProductParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateProductParamsWithHTTPClient(client *http.Client) *UpdateProductParams {
	var ()
	return &UpdateProductParams{
		HTTPClient: client,
	}
}

/*UpdateProductParams contains all the parameters to send to the API endpoint
for the update product operation typically these are written to a http.Request
*/
type UpdateProductParams struct {

	/*Body
	  Product data structure to Update or Create.
	Note: the id field is ignored by update and create operations

	*/
	Body *models.Product

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update product params
func (o *UpdateProductParams) WithTimeout(timeout time.Duration) *UpdateProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update product params
func (o *UpdateProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update product params
func (o *UpdateProductParams) WithContext(ctx context.Context) *UpdateProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update product params
func (o *UpdateProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update product params
func (o *UpdateProductParams) WithHTTPClient(client *http.Client) *UpdateProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update product params
func (o *UpdateProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update product params
func (o *UpdateProductParams) WithBody(body *models.Product) *UpdateProductParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update product params
func (o *UpdateProductParams) SetBody(body *models.Product) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
